name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    steps:
      - uses: actions/checkout@v4
      - name: Show C info
        run: gcc -dM -E -x c  /dev/null
      - name: Show C++ info
        run: g++ -dM -E -x c++  /dev/null
      - name: Run test
        run: |
          g++ -o test.exe test.cpp
          ./test.exe
