name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    steps:
      - uses: actions/checkout@v4
      - name: Test win
        shell: cmd
        if: runner.os == 'Windows'
        run: |
          foo && foo.cmd
          echo Hello
      - name: Test pwsh
        shell: pwsh
        if: runner.os == 'Windows'
        run: |
          $env:PATH="$($env:PATH);foo"
          $env:PATH
