name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          g++ -o foo.exe foo.c
      - name: Test win
        shell: cmd
        run: |
          where foo
      - name: Test win
        shell: cmd
        run: |
          foo
          foo.cmd
          echo Bar
      - name: Test pwsh
        shell: pwsh
        run: |
          $env:PATH="$($env:PATH);foo"
          $env:PATH
