name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    steps:
      - uses: actions/checkout@v4
      - name: Show env
        run: |
          echo "$SHELL"
          export SHELL=foo
          echo "$SHELL"
      - name: Show C info
        run: |
          touch foo.c
          gcc -dM -E -x c foo.c
      - name: Show C++ info
        run: |
          touch foo.cpp
          g++ -dM -E -x c++ foo.cpp
      - name: Run test
        run: |
          g++ -o test.exe test.cpp
          ./test.exe
